services:
  frontend:
    build:
      context: ./webApp
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - orchestrator 
    env_file:
      - .env 

  orchestrator:
    build:
      context: ./calculationService
      dockerfile: Dockerfile
    ports:
      - 8081:80
    env_file:
      - .env

  agent:
    build:
      context: ./megaFastAgent
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - orchestrator
